### ISSUE TITLE
unnecessary(?) warning about dbcache

### ISSUE THREAD

**Issue by stefanfoulis** [ecometrica/django-multisite#36]
Here a warning is issued if dbcache is used: https://github.com/ecometrica/django-multisite/blob/master/multisite/hacks.py#L75-L78
I don't understand point of this warning. If I'm using the db-cache, obviously accessing the cache will cause queries. Same for dummy cache. If I set the dummy cache, nothing will be cached.

I propose removing those warnings, since they just clutter up the output of legitimately configured projects.

:-)

**Comment by rebkwok** [comment]
Fixed by #55
