### ISSUE TITLE
Bump to Django 1.8

### ISSUE THREAD

**Issue by kousu** [ecometrica/django-multisite#39]
Right now `setup.py` says `Django>=1.6`. It still works back there---at least, the tests still pass, though I am not totally confident in them---while Django 1.6 and 1.7's [docs](https://docs.djangoproject.com/en/1.7/) warn "This document is for an insecure version of Django that is no longer supported. Please upgrade to a newer release!"

Worse, Django 1.6 and 1.7 are simply [not supported on python3](http://stackoverflow.com/questions/34827566/attributeerror-module-html-parser-has-no-attribute-htmlparseerror#36000103). I would like to drop support for these by bumping `setup.py` to `Django>=1.8`. Django 1.8 [is LTS](https://www.djangoproject.com/weblog/2015/apr/01/release-18-final/), which means standardizing on it is a safe bet.

Thoughts?

**Comment by pauricthelodger** [comment]
I think this makes sense. Maybe a release for #37 with a deprecation warning for 1.6 and 1.7?

**Comment by kousu** [comment]
Something like this in `__init__.py`?

```
if django.VERSION < (1,8):
    warnings.warn("Support for Django under 1.8 will be dropped in version 1.5",
                  DeprecationWarning)
```

**Comment by pauricthelodger** [comment]
Aye, that's probably a good spot for it. Maybe a PendingDeprecationWarning instead though? 1.5 makes sense as well, might be something we do a after 1.11 LTS is released?

**Comment by kousu** [comment]
Sure. I can't tell the difference. https://mail.python.org/pipermail/python-dev/2011-October/114199.html suggests they're identical at this point.

**Comment by pauricthelodger** [comment]
Between the PEP and that thread, I think you're right =)

**Comment by rebkwok** [comment]
<1.7 support dropped in #45
