### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by kousu** [ecometrica/django-multisite#40]
In light of #37 and #14, this project could benefit from running a continuous integration server. Over at https://github.com/ecometrica/django-hashedfilenamestorage/pull/4 a kindly soul has even laid out most of the groundwork for integrating these Django projects with Travis-CI and tox---which can replace `test_versions` by configuring and testing on multiple environments [just from a config file](https://github.com/Apkawa/django-hashedfilenamestorage/blob/1d2ff6f5395bba50d6fdd8b74158617616e1d43e/tox.ini#L4).

I look forward to being able to put one of those cute "Build Passing" icons on our README.

**Comment by rebkwok** [comment]
Fixed in PR #45
