### ISSUE TITLE
Doesn't work with django_debug_toolbar

### ISSUE THREAD

**Issue by pcoder** [ecometrica/django-multisite#48]
django-multisite does not seem to work with [Django debug toolbar](https://github.com/jazzband/django-debug-toolbar)

Steps to reproduce:
1. Install django-debug-toolbar (pip install django-debug-toolbar)
2. Add `debug_toolbar` to the INSTALLED_APPS in the project settings
3. Start the server ..

Result: 
The server fails to start without any errors.

**Comment by rebkwok** [comment]
I am running a project locally with both multisite and django-debug-toolbar and the debug toolbar is working fine, so I'm not sure this is a multisite problem.  Can you provide some more information on the errors you're seeing?
