### ISSUE TITLE
KeyError at / 1

### ISSUE THREAD

**Issue by igerko** [ecometrica/django-multisite#54]
I'm getting this errors in production.
For caching we use: redis-cache

Request Method: HEAD

```
File "/usr/local/lib/python3.5/site-packages/django/contrib/sites/models.py" in get_current
  65.             return self._get_site_by_id(site_id)

File "/usr/local/lib/python3.5/site-packages/django/contrib/sites/models.py" in _get_site_by_id
  37.         return SITE_CACHE[site_id]

File "/usr/local/lib/python3.5/site-packages/multisite/hacks.py" in __getitem__
  124.             raise KeyError(key)
```

**Comment by ziima** [comment]
Same here. Looks like a race condition in `_get_site_by_id`. We're not quite sure, how it happens. I suspect the cache may get invalidated/expired between the condition and the return statement.

**Comment by okolimar** [comment]
Yes it is a race condition, when you run in loop Site.objects.get_current() and invalidate cache in between, it throws this

**Comment by ziima** [comment]
For us it occurs way too often (several times a day) and we don't invalidate cache manually. It is also too often for records to expire.

**Comment by rebkwok** [comment]
This seems related to https://code.djangoproject.com/ticket/15894
It happens to us too on occasion, although we had thought it was related to our database routing set up.

**Comment by filwaitman** [comment]
:+1: 

Same issue here. Race-condition, in fact, seems to be the villain. I just optimized a project by creating a multiprocess setup and the amount of `KeyError`s increased drastically.

Thanks for the good job (and for this fix) @rebkwok !

**Comment by ziima** [comment]
Will there be a new release with this bug fixed?

**Comment by filwaitman** [comment]
@ziima already done I guess (1.6.0 on PyPI)

**Comment by ziima** [comment]
Oh, I got confused by the fact, that tag is not on the bump commit. Thanks for clearing that up.
