### ISSUE TITLE
Advantages of django-multisite

### ISSUE THREAD

**Issue by Morvarid** [ecometrica/django-multisite#57]
Would you please tell me what advantages django-multisite has compare to **Django Sites framework**? 
Thank you

**Comment by mvett11** [comment]
I believe the benefit is that you are able to access all of your sites running from one instance. Simply using Django Sites framework allows you to breakup your project onto to different sites, but to access them you need to set `SITE_ID` to the respective site in your `settings.py` file. With `django-multisite` you are able to set `SITE_ID` using `SiteID()` which uses Sites and Aliases to determine the `SITE_ID` value. This allows you to access any site from a single instance and database as opposed to multiple instance and a single database.
