### ISSUE TITLE
New PyPi release

### ISSUE THREAD

**Issue by tpazderka** [ecometrica/django-multisite#63]
Could you please release a new version with support for Django 2.2 on Pypi?

The latest release is over a year old and there have been many updates and fixes to the library.

**Comment by pauricthelodger** [comment]
@tpazderka - apologies for the delay on this, 1.7.0 has just been released with Django<3.0 support. We'll arrange another version soon for Django3.

**Comment by tpazderka** [comment]
Thanks!
