### ISSUE TITLE
What current version of Django does this support?

### ISSUE THREAD

**Issue by swallace21** [ecometrica/django-multisite#64]
Upgrading an old Django instance to the Django 2.x LTS release.

**Comment by damon-rand** [comment]
Should hopefully be fine. Please post any issues you find. We are not currently running it in production on 2.x but we do have it running successfully in a development environment for testing.

**Comment by pauricthelodger** [comment]
@swallace21 - we just released 1.7.0 on PyPI that supports the 2.2 LTS so hopefully you won't hit any issues :crossed_fingers:
